name: Scrape USAC schedules

on:
  schedule:
    - cron: "0 5 * * *" # todos los días a las 05:00 UTC
  workflow_dispatch: # permite lanzarlo manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          pip install requests browser-cookie3 beautifulsoup4
      - name: Run scraper
        run: |
          python scraper.py --output public/schedules.json
      - name: Commit JSON
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Actualiza schedules.json"
          file_pattern: public/schedules.json
